"""H1_2 Newton (Warp physics) sim2sim env config for RoboJuDo.

Newton analogue of :class:`H1_2MujocoEnvCfg`: same 27-DOF H1_2, driven through
Newton's ``SolverMuJoCo`` with implicit PD (matches the H1_2 BUILT_IN_PD
checkpoints). ``newton_xml`` points at the composed **H1_2 + Ability-hands**
scene (``h1_2_box_feet_ability_hands.xml``, generated by
``scripts/compose_h1_2_ability_hands.py``) so the finger DOFs the lift-teacher
policy conditions on are physically present; ``cfg.xml`` (the RoboJuDo h1_2 copy)
is still used for FK via MujocoKinematics (MuJoCo's lenient parser).
"""

from robojudo.config import ASSETS_DIR
from robojudo.environment.env_cfgs import NewtonEnvCfg

from .h1_2_env_cfg import H1_2EnvCfg


class H1_2NewtonEnvCfg(H1_2EnvCfg, NewtonEnvCfg):
    env_type: str = NewtonEnvCfg.model_fields["env_type"].default
    is_sim: bool = NewtonEnvCfg.model_fields["is_sim"].default

    # Composed H1_2 + Psyonic Ability-hands scene (fingers attached at the
    # wrist_yaw links). Newton's strict-ElementTree parser loads this; the plain
    # RoboJuDo h1_2 copy is NOT ElementTree-parseable (see NewtonEnvCfg.newton_xml).
    newton_xml: str = (ASSETS_DIR / "robots/h1_2/h1_2_box_feet_ability_hands.xml").as_posix()

    update_with_fk: bool = True
    use_implicit_pd: bool = True
